apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  labels:
    app: redis
spec:
  type: NodePort
  ports:
    - port: 6379
      nodePort: 30002
      protocol: TCP
  selector:
    app: redis
    
